# =========================================================================
#   Ceedling - Test-Centered Build System for C
#   ThrowTheSwitch.org
#   Copyright (c) 2010-26 Mike Karlesky, Mark VanderVoord, & Greg Williams
#   SPDX-License-Identifier: MIT
# =========================================================================

require 'ceedling/constants'
require 'ceedling/file_path_utils'

class ConfiguratorPlugins

  constructor :file_wrapper, :system_wrapper

  attr_reader :rake_plugins, :programmatic_plugins, :config_plugins

  # Content that makes a directory a plugin, as globs beneath that directory
  PLUGIN_CONTENT = {
    config_ruby: ['config', '*.rb'],
    config_yaml: ['config', '*.yml'],
    lib:         ['lib', '*.rb'],
    rake:        ['*.rake']
  }.freeze

  def setup
    @rake_plugins = []
    @programmatic_plugins = []
    @config_plugins = []
  end


  # Override to prevent exception handling from walking & stringifying the object variables.
  # Object variables are gigantic and produce a flood of output.
  def inspect
    return self.class.name
  end


  # Adds every load path to Ruby's load path, then finds each enabled plugin in the first
  # load path holding any plugin content. Returns the found paths, keyed :<plugin>_path.
  def process_aux_load_paths(config)
    load_paths = config[:plugins][:load_paths]
    load_paths.each { |path| @system_wrapper.add_load_path( path ) }

    return config[:plugins][:enabled].each_with_object( {} ) do |plugin, plugin_paths|
      path = find_plugin( plugin, load_paths )
      plugin_paths[:"#{plugin}_path"] = path if path
    end
  end


  # Gather up and return .rake filepaths that exist in plugin paths
  def find_rake_plugins(config, plugin_paths)
    found = plugins_with_file( config, plugin_paths ) { |plugin, path| File.join( path, "#{plugin}.rake" ) }
    return @rake_plugins = found.map { |plugin, _, file| { plugin: plugin, path: file } }
  end


  # Gather up names of .rb `Plugin` subclasses and root paths that exist in plugin paths + lib/
  def find_programmatic_plugins(config, plugin_paths)
    found = plugins_with_file( config, plugin_paths ) { |plugin, path| File.join( path, 'lib', "#{plugin}.rb" ) }
    return @programmatic_plugins = found.map { |plugin, path, _| { plugin: plugin, root_path: path } }
  end


  # Gather up and return config .yml filepaths that exist in plugin paths + config/
  def find_config_plugins(config, plugin_paths)
    found = plugins_with_file( config, plugin_paths ) { |plugin, path| File.join( path, 'config', "#{plugin}.yml" ) }
    return @config_plugins = found.map { |plugin, _, file| { plugin: plugin, path: file } }
  end


  # Gather up and return default .yml filepaths that exist on-disk
  def find_plugin_yml_defaults(config, plugin_paths)
    found = plugins_with_file( config, plugin_paths ) { |_, path| File.join( path, 'config', 'defaults.yml' ) }
    return found.to_h { |plugin, _, file| [plugin.to_sym, file] }
  end


  # Gather up and return defaults generated by Ruby code in plugin paths + config/. Each
  # defaults file defines get_default_config(), which is called as soon as it loads.
  def find_plugin_hash_defaults(config, plugin_paths)
    found = plugins_with_file( config, plugin_paths ) { |plugin, path| File.join( path, 'config', "defaults_#{plugin}.rb" ) }

    return found.to_h do |plugin, _, _|
      @system_wrapper.require_file( "defaults_#{plugin}.rb" )
      [plugin.to_sym, get_default_config()]
    end
  end

  ### Private ###

  private

  # The plugin's directory in the first load path that holds any plugin content. Ruby
  # files beneath its config/ and lib/ are then loadable by name.
  def find_plugin(plugin, load_paths)
    load_paths.each do |root|
      path    = File.join( root, plugin )
      content = plugin_content( path )
      next if content.empty?

      @system_wrapper.add_load_path( File.join( path, 'config' ) ) if content.include?( :config_ruby )
      @system_wrapper.add_load_path( File.join( path, 'lib' ) )    if content.include?( :lib )
      return path
    end

    return nil
  end

  # #104 -- FilePathUtils.glob escapes literal brackets in a load path, so a bracket-named
  # directory is matched rather than read as a glob character class
  def plugin_content(path)
    return PLUGIN_CONTENT.keys.reject { |kind| @file_wrapper.directory_listing( FilePathUtils.glob( path, *PLUGIN_CONTENT[kind] ) ).empty? }
  end

  # Each enabled plugin with a found path whose file, named by the block, exists, as
  # [plugin, plugin path, file]
  def plugins_with_file(config, plugin_paths)
    return config[:plugins][:enabled].filter_map do |plugin|
      path = plugin_paths[:"#{plugin}_path"]
      next if path.nil?

      file = yield( plugin, path )
      [plugin, path, file] if @file_wrapper.exist?( file )
    end
  end

end
