# =========================================================================
#   Ceedling - Test-Centered Build System for C
#   ThrowTheSwitch.org
#   Copyright (c) 2010-24 Mike Karlesky, Mark VanderVoord, & Greg Williams
#   SPDX-License-Identifier: MIT
# =========================================================================

---
# Continuous Integration Workflow
name: pre-commit

# Triggers the workflow on push or pull request events for master & test branches
on:
  push:
    branches:
      - 'master'
      - 'test/**'
  pull_request:
    branches: [ master ]
  workflow_dispatch:


# Needed by softprops/action-gh-release
permissions:
  # Allow built gem file push to Github release
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    # based on https://pre-commit.com/#github-actions-example
    - name: set PY
      run: echo "PY=$(python3.12 -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV
    - name: Cache pre-commit
      uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit
        key: pre-commit| ${{ env.PY }} | ${{ hashFiles('.pre-commit-config.yaml') }}
    - name: Install pre-commit
      # install fixed version for reproducibility
      run: python3.12 -m pip install pre-commit==3.7.1
    - name: Run pre-commit
      run: pre-commit run --all-files
